name: Test Documentation Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install sphinx
          sudo apt-get install -y pandoc
          pip install pandoc
          pip install nbsphinx
          pip install pydata-sphinx-theme==0.7.2
      - name: Sphinx build
        run: |
          cd docs
          make html
